### ISSUE TITLE
problems with Java versions ≥ 9

### ISSUE THREAD

**Issue by jmtd** [hrehfeld/QuakeInjector#114]
Java 9+ introduces modules and moves some stuff out of the default classpath. In particular quakeinjector throws the following

```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javax/xml/ws/http/HTTPException
```

[the solution is probably something like this](
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j) when loading the JAR:

> java --add-modules java.xml.ws quakeinjector.jar

However that doesn't work with Java 11 (a different module name perhaps? or maybe the module has been deleted by 11?)

Perhaps there's a way of assembling the JAR so it can indicate what modules it needs

**Comment by jonatkinson** [comment]
To add some more detail here, using the following Java on OSX:

```
jon@macbook ~/S/q/quakeinjector-alpha03> java --version
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

The trace is as follows:

```
jon@macbook ~/S/q/quakeinjector-alpha03> java -jar quakeinjector.jar
Reading configuration...
Setting downloadpath: /Users/jon/quake/downloads
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javax/xml/ws/http/HTTPException
	at de.haukerehfeld.quakeinjector.QuakeInjector.doParseDatabase(QuakeInjector.java:334)
	at de.haukerehfeld.quakeinjector.QuakeInjector.parseDatabaseAndSetList(QuakeInjector.java:520)
	at de.haukerehfeld.quakeinjector.QuakeInjector.init(QuakeInjector.java:242)
	at de.haukerehfeld.quakeinjector.QuakeInjector.access$1500(QuakeInjector.java:66)
	at de.haukerehfeld.quakeinjector.QuakeInjector$21.run(QuakeInjector.java:896)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.http.HTTPException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 18 more
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javax/xml/ws/http/HTTPException
	at de.haukerehfeld.quakeinjector.QuakeInjector.doParseDatabase(QuakeInjector.java:334)
	at de.haukerehfeld.quakeinjector.QuakeInjector.parseDatabaseAndSetList(QuakeInjector.java:520)
	at de.haukerehfeld.quakeinjector.QuakeInjector.access$200(QuakeInjector.java:66)
	at de.haukerehfeld.quakeinjector.QuakeInjector$2.actionPerformed(QuakeInjector.java:174)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.http.HTTPException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 42 more
```

**Comment by SpiritQuaddicted** [comment]
> I had problems compiling and running for the first time last week. On examination, I think a best solution would be to create a new HTTPException exception within the project because the local code is the only code throwing it.

That sounds reasonable I think. I have no idea about Java. Would you be willing to do that? I would simply add you as developer so you can work directly in the repo. :)

**Comment by KhevinLiepp** [comment]
Here is a PR for this one:
https://github.com/hrehfeld/QuakeInjector/pull/118

**Comment by duganchen** [comment]
That got it working with Java 11. This gets it working with Java 13:
https://github.com/hrehfeld/QuakeInjector/pull/119
