### ISSUE TITLE
Dark Mode [FEATURE]

### ISSUE THREAD

**Issue by SHADOWELITE7** [hrehfeld/QuakeInjector#141]
I just started using this program for Quake and I really like it. But I think it would be better if there was an option to have a dark mode (Possibly since this is for Quake, maybe a [Quake color palette](https://quakewiki.org/wiki/Quake_palette) being used for dark mode).

**Comment by SpiritQuaddicted** [comment]
That would be nice! I have no idea about Java and Swing, maybe https://github.com/weisJ/darklaf would be an option?

**Comment by johnnycz** [comment]
Solved in https://github.com/hrehfeld/QuakeInjector/compare/master...johnnycz:QuakeInjector:ui-follow-system-theme

**Comment by SpiritQuaddicted** [comment]
I am clueless with gradle so maybe it is an error at my end, but I get this error if I try to run a compilation of that branch:

```
No build commit found, attempting to read from props
Build commit is 
No build commit found, attempting to read from props
Build commit is 
Couldn't load config: java.lang.NoClassDefFoundError: com/github/weisj/darklaf/theme/Theme
java.lang.NoClassDefFoundError: com/github/weisj/darklaf/theme/Theme
        at de.haukerehfeld.quakeinjector.gui.UIThemeOption.<clinit>(UIThemeOption.java:16)
        at de.haukerehfeld.quakeinjector.Configuration$UIThemeConfiguration.<init>(Configuration.java:192)
        at de.haukerehfeld.quakeinjector.Configuration.<init>(Configuration.java:205)
	at de.haukerehfeld.quakeinjector.QuakeInjector$1.doInBackground(QuakeInjector.java:123)
	at de.haukerehfeld.quakeinjector.QuakeInjector$1.doInBackground(QuakeInjector.java:122)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:305)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:342)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.github.weisj.darklaf.theme.Theme
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 11 more
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Config not initialised!
	at de.haukerehfeld.quakeinjector.QuakeInjector.getConfig(QuakeInjector.java:881)
	at de.haukerehfeld.quakeinjector.QuakeInjector.loadTheme(QuakeInjector.java:172)
	at de.haukerehfeld.quakeinjector.QuakeInjector.<init>(QuakeInjector.java:139)
	at de.haukerehfeld.quakeinjector.QuakeInjector$25.run(QuakeInjector.java:934)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by johnnycz** [comment]
Sounds like it does not have the new jars from the new dependency on its classpath. Grab all the lib/darklaf*.jar files from build/distributions/QuakeInjector.zip/lib and put them into the lib dir where you're running Quake Injector from.

**Comment by johnnycz** [comment]
The .bat file also needs to be updated. Best bet is to generate a new distribution zip file (./gradlew distZip) and extract that into its own folder and run from there. I did not get to test this on Windows yet, so its possible there's some other issue if none of the above helps.

**Comment by SpiritQuaddicted** [comment]
The new release has dark mode, check it out!

https://github.com/hrehfeld/QuakeInjector/releases/tag/alpha08
