### ISSUE TITLE
Files with spaces in the filename cannot be downloaded

### ISSUE THREAD

**Issue by SpiritQuaddicted** [hrehfeld/QuakeInjector#143]
I decided to not care anymore and uploaded a new release with spaces in its filename to Quaddicted: `ad_mfk_dreamdem (v1.1).zip`. The Injector seems not able to handle it:

```
Couldn't load image https://www.quaddicted.com/reviews/screenshots/ad_mfk_dreamdem (v1.1)_injector.jpg
Required package ad_v1_80p1final already installed.downloadpath null, returning default
Downloading to /home/user/quake/downloads/ad_mfk_dreamdem (v1.1).zip
Downloading <https://www.quaddicted.com/filebase/ad_mfk_dreamdem (v1.1).zip>
Error downloading file, removing...done.
unhandled exception from install workerde.haukerehfeld.quakeinjector.HTTPException
de.haukerehfeld.quakeinjector.HTTPException
	at de.haukerehfeld.quakeinjector.Download.connect(Download.java:72)
	at de.haukerehfeld.quakeinjector.DownloadWorker.doInBackground(DownloadWorker.java:53)
	at de.haukerehfeld.quakeinjector.DownloadWorker.doInBackground(DownloadWorker.java:32)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Done saving installedmaps
```

**Comment by krakissi** [comment]
Error is in Download.java at line 41. When you create a new URL like that it will not automatically escape/encode anything. You need the path to be percent encoded.  See here: https://en.m.wikipedia.org/wiki/Percent-encoding

Spaces should be converted to %20. Java has a built in URLEncoder class, but it is designed to encode query string parameters and will escape spaces as + instead of %20.

This is a common bug in Java software and there is no great, truly correct way to solve it. What you should actually do is follow an example from here: https://stackoverflow.com/questions/10786042/java-url-encoding-of-query-string-parameters

```
You need to first create a URI like:

String urlStr = "http://www.example.com/CEREC® Materials & Accessories/IPS Empress® CAD.pdf"
URL url= new URL(urlStr);
URI uri = new URI(url.getProtocol(), url.getUserInfo(), url.getHost(), url.getPort(), url.getPath(), url.getQuery(), url.getRef());

Then convert that Uri to ASCII string:

urlStr=uri.toASCIIString();

```

**Comment by SpiritQuaddicted** [comment]
Fixed by @pettyalex in https://github.com/hrehfeld/QuakeInjector/pull/144, thank you!
